name: deploys-pr-slack-reminders
on:
  pull_request:
    types:
      - labeled
jobs:
  trigger-slack: # pulse-eng-undeployed-prs is subscribed to this no-op job
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'deploy/reminded' }}
    steps:
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "PR <${{ github.event.pull_request.url }}|#${{ github.event.pull_request.number }}> by @${{ github.event.pull_request.user.login }} has not been deployed. It was merged on ${{ github.event.pull_request.mergedAt }}."
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.UNDEPLOYED_PRS_SLACK_WEBHOOK_URL }}
